version: "3"
services:
  app:
    build:
      context: ../next-sample
    ports:
      - 18001:3000
    volumes:
      - ../next-sample:/app
    command: sh -c "npm install && npm run dev"
    # command: tail -f /dev/null
  storybook:
    build:
      context: ../next-sample
    ports:
      - 6007:6006
    volumes:
      - ../next-sample:/app
    command: sh -c "npm install && npm run storybook"
    # command: tail -f /dev/null
